### ISSUE TITLE
update forcetemp with daily data when possible

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#130]
@MoralesCastilla 

Hi Nacho!

I have another OSPREE request, I am hoping this is not so bad since you are doing GDD, but let me know if my hope is incorrect ....

If you run analyses/bb_analysis/source/bbdataplease.R (you need to set the working directory, check out the start of bbmodels_stan.R) and then run the commented out bit at the end you'll see a bunch of data we could have if we filled in ambient temp ... could you pull build mean temp from start of experiment (this is the date we already have built in the GDD code) through to budburst (again, done in GDD) and calculate the mean temp? Then create it as an output file (or some R code) in such a way that we can drop into the ospree_clean_withchill_BB.csv file. 

Eventually we should probably add it to analyses/bb_analysis/cleaning/clean_ambientforcing.R so if you can do that, it would be great.

**Comment by MoralesCastilla** [comment]
I have pushed a script that extracts ambient temp: `bb_analyses/get_meantemp_ambient.R`. It should be checked and then I can insert it into clean_ambientforcing.R.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla I didn't see any major errors, so I mostly pushed jus changes to the comments. But a few things we should do:

I think we should change 44-47 (below):

```
## get all the BB data and format a little
dat.all <- read.csv("output/ospree_clean_withchill_BB.csv", header=TRUE)
dat.some <- subset(dat.all, respvar.simple=="daystobudburst"|respvar.simple=="percentbudburst")
bbdat <- subset(dat.some, response.time!="")
```
Right now it references ospree_clean_withchill_BB.csv, but if we then use the output of this R file (get_meantemp_ambient.R) within our BB cleaning folder it's circular: the BB cleaning creates ospree_clean_withchill_BB.csv which uses output from get_meantemp_ambient.R which uses ospree_clean_withchill_BB.csv.

To fix it I suggest we:

1. Move get_meantemp_ambient.R to bb_analysis/cleaning and mention what it does explicitly in the README in that folder (including noting in the README that this file assumes users are working only with daystobudburst and percentbudburst and where response.time!=""). 
2. Reference ospree_clean_withchill.csv instead of ospree_clean_withchill_BB.csv in lines 44-47.
3. When you do add this to output (i.e., bbdata_avgTemp.csv) into bb_analysis cleaning; make a new file called clean_ambientforcingfromdailyclimate.R so it's easier for everyone to see how we did this.

Add a comment to line 91 about the warnings, are they okay?

Also, @AileneKane Could you take a quick look at this file (get_meantemp_ambient.R) also? I want a second set of eyes on cleaning but also to make sure we're using data that you are updating or that we somehow also centralize the creation of the climate data used.

Thank you both!

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane 
Let's check in on this tomorrow!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver 

The following tasks from above have been addressed:

> 1. Move get_meantemp_ambient.R to bb_analysis/cleaning and mention what it does explicitly in the README in that folder (including noting in the README that this file assumes users are working only with daystobudburst and percentbudburst and where response.time!=""). 
Done
> 
> 2. Reference ospree_clean_withchill.csv instead of ospree_clean_withchill_BB.csv in lines 44-47.
> 
Done

I'm not fully sure what would the contents of `clean_ambientforcingfromdailyclimate.R` be. Would we use that to replace `get_meantemp_ambient.R`?

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
I have generated `clean_ambientforcingfromdailyclimate.R` and sourced it from `bb_cleanmergeall.R`, I have not activated it yet as I was not sure where in the cleaning code sequence to place it (after clean_ambientforcing.R?). 
It would be nice if any of you could check this.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Yes! You picked the correct place to source it. 
But, when I tried the code today but got an error at i=1961 (I ran bb_cleanmergeall.R up to after 5a, then tried your code -- after turning off the opening lines). Can you check this? Can you also write the code to add it to the rest of the data? Then I will check it again.

**Comment by lizzieinvancouver** [comment]
@AileneKane 
Your changes to the dailyclimate naming etc. looked good, one last thing though -- should we change the name of the output folder (still output/pmp I think?). If you do, please let Nacho know so he can update his code.

**Comment by AileneKane** [comment]
We should rerun these now that we have improved climate data

**Comment by AileneKane** [comment]
And, yes, I should update the name! I will check with everyone about this today!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane I have now corrected `clean_ambientforcingfromdailyclimate.R` to avoid it from stopping, and to include the variable avg_bbtemp into the database d. I have activated it to be sourced from `bb_cleanmergeall.R`. Once someone checks on it, we should be ok to close this one.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Thank you!
@AileneKane Would you take a look at the code? I can then take one last look and we can close this!

**Comment by AileneKane** [comment]
I have checked Nacho's code, and I have a few questions:
1) I get a warning: "In which(clim.i$year == year.i & clim.i$doy2 == doy.i):which(clim.i$year ==  ... :
  numerical expression has 2 elements: only the first used". It happens in the ## Loop to add mean temp to each line in bb,  Lines 70-93 

2) The code relies on several files  that have not been updated since July (daily_expchill.csv, percbb_clim_pmpA, percbb_clim_pmpB, percbb_clim_pmpC, percbb_clim_pmpD, created in bb_daily_dataprep) and so they all need to be updated. Where we should add this to the workflow so that these files stay up to date? Should I add it to the bb_cleanmergeall.R file or keep it separate? I can make an issue for myself to go through everything to update it, and change all the names to remove pmp at the same time.

3) The "bbcleaning_README" file needs to be updated, as it does not include clean_ambientforcingfromdailyclimate.R

**Comment by MoralesCastilla** [comment]
@AileneKane 
1. Also, as I pointed out in the stop message, there is no need to worry about the warning, which comes from an if statement with two inputs out of which only the first is utilized. 
2. Not sure about the update of pmp climate files, do we need to do that?
3. I have now updated the README file to include the script.

**Comment by lizzieinvancouver** [comment]
@AileneKane will next:

1. Move the major climate data pulling code to the chilling work.
2. Adjust the clean_ambientforcingfromdailyclimate.R in bb_analysis/cleaning so it just updates the forcing column.

**Comment by lizzieinvancouver** [comment]
Update on Schwartz ... climate file was just missing! Ailene has updated it on her drive.

**Comment by lizzieinvancouver** [comment]
@AileneKane Move the daily*.csv to dailyclim folder and update paths!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Check in on this and see if we're close to closing! Ailene thinks the daily data is all updated.

**Comment by cchambe12** [comment]
I've looked over the code to make sure that the above three criteria were met...

It seems that everything checks out although I'm not sure if the clean_ambientforcingfromdailyclimate.R is updating the forcetemp column. If I am missing it somewhere then everything else checks out and I think we can close this.

**Comment by dbuona** [comment]
@AileneKane Check that forcetemp column is updating,=. @lizzieinvancouver too.

**Comment by AileneKane** [comment]
i was not able to update the forcing with the new daily climate files...something in clean_ambientforcingfromdailyclimate.R is now broken (it doesn't like something in the updated files) and i'm not sure what...i worked on it a bit but need to take a break tomorrow to work on other things, so may not be able to return to it for a day or two. If anyone else wants to take a look, please do!

**Comment by lizzieinvancouver** [comment]
@AileneKane Hi Ailene! 
Here's my update on what looks to be stuck in clean_ambientforcingfromdailyclimate.R:
- line 91, references 'stn' which I changed to 'uniqueID' (but please double check)
- after that it fails on line 98, specifically this piece:
`which(clim.i$year==year.end.i & clim.i$doy==doy.end.i)`
for the first 1 (ashby) it wants to gather data that ends on doy 93 of year 1957, but when I look at the clim.i (subsetted climate data) it only gives the calendar year of 1956.
Hopefully this helps? Happy to help more, let me know what I can do. I will push my small edits now.

**Comment by lizzieinvancouver** [comment]
@AileneKane Nice work! We're getting close!

**Comment by AileneKane** [comment]
I fixed the daily pulling code i think, and am rerunning everything now so hopefully we will have ore complete data later today. It would be helpful for @MoralesCastilla or someone to look at the clean_ambientforcingfromdailyclimate.R and check that my modifications are ok.

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks! I am going to make some edits to bb_cleanmergeall.R and related files. We should not add simple lines of code to this file (e.g., the new 9) but instead should put that in clean_bbperctodays.R where it already should have happened.

**Comment by AileneKane** [comment]
I have updated the daily file again, but in doing so discovered that issues with 4 studies were not fixed by my latest round (fu12, "gunderson12" "skuterud94" "basler12"). I will get these fixed this week, but they are unlikely to be done by our meeting, given the long time that it takes to generate this file. I also have a few questions:
1) I am treating basler12 (in which forcing = "basler12") the same as ambient (since we use Tmean to calculate forcing, i think). Is that ok?
2) how to deal with skuterud94, in which forcing ="mean of 9, 12, 15"?

**Comment by AileneKane** [comment]
Cat is going to look into basler12- it is more complicated than that!

**Comment by AileneKane** [comment]
@cchambe12, it looks like you have already looked at baller and fixed it in “clean_ambientforcing.R” 
 @lizzieinvancouver  this made me realize that perhaps i should be using the version of ospree AFTER ambientforcing has been cleaning in the bb_daily_dataprep.R file. It starts with clean_ospree_withchill currently.

**Comment by AileneKane** [comment]
After looking at skuterud94, it is not possible to tell explicitly which forcing temp goes with which budburst date.

**Comment by AileneKane** [comment]
@cchambe12 @lizzieinvancouver 
I uncovered another mistake today! I take partial responsibility because I entered the original site into ospree wrong (schnabel87). It has also had some cleaning done to it that made it "wrong-er" - (in clean_forecetemp) things that were supposed to be ambient were changed to 24- not sure why!
Anyway, I'm seeking permission to fix this in the cleaning code! It needs to have several rows deleted (the photoperiod gradually decreased over time in some treatments and when i originally did the data entry, i entered each experienced photoperiod as a separate row, even though it should have just been 1 row). I remember talking with Tim about this during the original entry. Anyway, this could account for some of the weird patterns in the data...

**Comment by lizzieinvancouver** [comment]
@AileneKane You have my approval!

**Comment by AileneKane** [comment]
Ok, I have corrected the schnaebel87 data in clean_photo.R and clean_forcetemp.R, have rerun cleanmerge_all.R and chillmerge_all.R to create new versions of ospree_clean.csv and ospree_cleanwithchill.csv. Next step is to add the super weird treatments they did to bb_daily_dataprep.R

**Comment by AileneKane** [comment]
I have updated this with the latest data! There are still 7 studies that are missing some daily temperature data to calculate forcing (calme94, campbell75, hawkins12, heide12,partanen01,skre08, and skuterud94). I'm not so worried about skuterud94, since I know we can't distinguish the forcing treatments to use it anyway, but if we want to have ambient climate data to calculate forcing for any of the other 6 studies, then i will look into why they are missing data. (have looked int calm94 and hawkins12 already and for some reason we do not have climate data for all of their lat/longs).

**Comment by lizzieinvancouver** [comment]
@AileneKane Thanks for this! Hopefully we can go through it tomorrow. One other question, in working yesterday I noticed the rows in ospree_clean_withchill.csv went down a little, from 12743 to 12693, does this change make sense to you?

**Comment by lizzieinvancouver** [comment]
@AileneKane Re: 

> Question: I am not getting creating a daily climate record for any budburst event that says "no response" in response.time. is that ok?

It's okay for now, but if we ever add them back in we'll need the data .... right now the ones that are just no response because they never leafed out are re-coded to 999 in clean_respvarmore.R

**Comment by AileneKane** [comment]
Yes, it does make sense that the rows went down from 12743 to 12693. These are the erroneous rows that I removed from schnabel87.

**Comment by AileneKane** [comment]
fixed code for calme94, campbell75, and partanen01 in bb_daily_dataprep.R. STill need to fix hawkins12, heide12,skre08, and skuterud94 and then rerun code

**Comment by lizzieinvancouver** [comment]
@AileneKane In running bb_analysis/cleaning/clean_ambientforcingfromdailyclimate.R from the main BB cleaning code today I got this error at counter 2804:

```
Error in which(clim.i$year == year.i & clim.i$doy == doy.i):which(clim.i$year ==  : 
  argument of length 0
```

**Comment by AileneKane** [comment]
@lizzieinvancouver I have fixed this problem, and rerun the bb_cleanmergeall code.
