### ISSUE TITLE
Centralize lat/long cleaning?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#131]
I just found hawkins12, long of 427.78 for Prince Rupert should be -127.78 and since they are WEST, shouldn't all of the hawkins12 longitudes be negative?!

**Comment by AileneKane** [comment]
I will move the cleaning that is currently done in "chililng" to the "cleaning"folder and make sure that this change is included that lat/long cleaning

**Comment by AileneKane** [comment]
I'm sure you are right about the longitude, though i did not check them. We did not fix all of these in the earlier cleaning code because the climate pulling code corrects for it. Let me know if you want me to go through the lat/long and actually clean each of these to fix the postive/negative errors in longitude. do you want me to correct hawkins12 for this? There are likely to be other sites that also have the wrong sign, i imagine.

**Comment by lizzieinvancouver** [comment]
@AileneKane 

The ideal thing would be to pull out whatever cleans the lat/long and move it to the main cleaning folder, then delete it from your cleaning in the chilling folder. Do you think that is possible or way too much of a headache?
After that I think we could try to split up more cleaning between the two of us if that would help?

**Comment by AileneKane** [comment]
the cleaning code for north america is easy to transfer from the chilling code (it simply multiplies positive longitudes by -1 since all north american sites are negative)- and i've done that. for the european sites, it is a bit more complicated- several of them seem to just be wrong (mostly  in  the growing.long column). they will require more sleuthing and going back to the paper. i can do it but it will take a bit longer.

**Comment by lizzieinvancouver** [comment]
@AileneKane Great! Let's move what we can and then decide how best to tackle more of the hand cleaning ....

**Comment by AileneKane** [comment]
3/4 of the bizarre growing longitudes are from heide93. I have fixed those by hand in cleaning_latlong.R . it's  alittle disconcerting because i have no idea where the misentered growing lat/longs came from. the paper says "The experiments were conducted at As (59°30'N)...Young trees of local origin..." so, i think the growing lat-long should be the same as the provenance lat-long for all. 

the 4th growing latitude that is negative for europe is nienstaedt66, which seems to be a study conducted at unvirsity of wisconsin but of species of european provenance. i changed the continent to north america for this one (in the cleaning_latlong.R files)- does that seem appropriate?

**Comment by lizzieinvancouver** [comment]
@AileneKane 
Hi Ailene! 
I just did made a bunch of edits to get your cleaning lat/long code to run. Had you tried running it from within the main cleaning folder (and file)? If not, then I am a little less worried about the edits, but either way, can you check out commit 51c7e28e1b84e492453f2f1aa914456467ca1bea and see if it looks okay to you? I will try to run the climate code tomorrow AM.

**Comment by AileneKane** [comment]
Your edits look fine to me. I just ran it from the main cleaning folder and it seemed to work fine, but I'm curious what you were worried about, since most of the edits looked minor to me. i changed the order of things in the main cleaning file so that the lat/long cleaning happens before the check for duplicates. this seemed important to me in part because of the extra column created be the duplicate checking code (I think the late/longs in this column and the provenance or growing lat/long column should match).
Let me know if there is anything else you want me to do with this!

**Comment by lizzieinvancouver** [comment]
@AileneKane I should have staged the commits, I did some super minor edits to make your code more readable (it's really helpful for others reading your code if it has more spaces and lineskips, and you should indent commands that runs over one linelength). But then I had a bunch of actual errors related to things like this:

d$growing.lat[which(d$continent=="europe" & as.numeric(d$growing.long)==-81.9372),] <-  d$provenance.lat[which(d$continent=="europe" & as.numeric(d$growing.long)==-81.9372)]

Unless I deleted the comma here (and many others) the whole line of code errored (because you are referencing one column already). Did this ever run for you?

Also this line:

d[d$datasetID=="hawkins12" & d$population=="Prince Rupert 33" &
    d$provenance.long=="-127.78",]$provenance.long <- -127.78

Needed to reference replacing 427.78 with -127.78 so that errored instead. Those were the big ones. 

Did you try running cleanmerge_all.R since you swapped things? It's important to always run any code one last time before you push it. Can you also update _cleaningREADME.txt if you have made changes to cleanmerge_all.R?

**Comment by AileneKane** [comment]
@lizzieinvancouver thank you for the details! I'm not sure what happened but i think it was a commit error of some kind- perhaps i didn't save and close the file before committing it last time as it ran with no errors on my computer prior. in any case, i have looked through it and rerun, and it seems fine. i also updated _cleaningREADME.txt. thank you for your work on this!

**Comment by AileneKane** [comment]
Perhaps someone else should check this before we close this task?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Check code and close if it looks good!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane I've just checked this code and works nicely. Closing!
