### ISSUE TITLE
what is up with data in guak98?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#145]
In checking daystobudburst vs. dayofyeartobudburst Nacho noticed the data from Fig. 5 looks a little off -- not sure why some of the dates are in the 30s (which would be in February ...).

**Comment by cchambe12** [comment]
@lizzieinvancouver @MoralesCastilla 
I think this looks fine... they started observing the buds either in mid-February or March 4 and it looks like the response.time values are the time since those start dates. They ended the experiment on June 3rd, which is why there are 90 day values. Most of those inputs are at or close to 100% budburst.

**Comment by lizzieinvancouver** [comment]
Sounds fine.
