### ISSUE TITLE
add experimental chilling hours -- discuss at retreat!

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#150]
to final calculation of chilling units @dbuona please point out file

**Comment by AileneKane** [comment]
@dbuona I just [updated the chilling ](https://github.com/lizzieinvancouver/ospree/commit/e98f4e1a87f58b11f46016d7fab64172d7b31887) to include the four sites that reported field chilling using the Utah model  ("biasi12"    "cook00b"    "heide93"    "skuterud94")
This was added to lines 126-127 of the totalchilcalcs.R script, if you want to check it out.

Other than that, I didn't see what other chilling could be added, because all the other studies use weird units. Please let me know if I am missing something and need to go back!

**Comment by lizzieinvancouver** [comment]
Other studies use: Carolina units, days above some threshold (0 or 8 degrees). We can't use these sadly.

**Comment by lizzieinvancouver** [comment]
Dan will work on zeroes for expchill, and a list of what has fieldchill... then Ailene will update (and check why some zeroes change to NA).

**Comment by dbuona** [comment]
@AileneKane @lizzieinvancouver  I am thinking about the best way to imput 0 experimental chilling. For several studies, (sogaard08, thielges75, caffarra11b) the $chilldays column is 0, but NA's are the output for all experimental chilling columns. I feel like I don't know anything about how chilling was calculated, so I am not sure if this is an easy fix or not during the chilling code.
Basically, I am not sure if I should fix these for just bb_analysis post chilling calculations or the should be fixed in the chilling code itself. Maybe we can touch base on this in the coming week?

**Comment by AileneKane** [comment]
@dbuona @lizzieinvancouver I think these are showing up as NAs because the default is to require both chilldays AND chilltemp (i.e. chilling is calculated by multiplying these two columns together). I will change the code so that if chilldays=0, chilling=0. I suppose all three metrics should equal 0, correct (e.g. Utah, Chillhours)?

**Comment by dbuona** [comment]
@AileneKane That sounds great. I think that will absorb a good amount of NA's as a whole.

**Comment by AileneKane** [comment]
I think this is now done!

**Comment by lizzieinvancouver** [comment]
@AileneKane @dbuona One point to discuss tomorrow: checking that if chilldays=0 chilling then Utah model, chillhours etc. should all equal 0 (remind me!).

**Comment by dbuona** [comment]
We thought about it. And...yes. Chilldays 0 will make the models be 0.
