### ISSUE TITLE
make 3D phenofit figure

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#165]

**Comment by lizzieinvancouver** [comment]
- X: shift in space (apply mean shift to each grid cell)
- Y: shift in time (calculate change in photoperiod at same lat/long)
- Z: change in photoperiod

**Comment by cchambe12** [comment]
@AileneKane @MoralesCastilla 

I updated the 3dplots_R.R (/analyses/photoperiod) script and added two .png files - one for FAGSYL (/photoperiod/figures/FAGSYL_shifts.png) and one for QUEROB (/photoperiod/figures/QUEROB_shifts.png). I tried to add OSPREE data onto the plots but I'm not sure if I did it correctly.. would either or both of you mind checking through my code when you get a chance to make sure it looks okay? I'm happy to Skype as well if that's easier!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Super cool plots! It actually looks like the geographical shift causes a bigger change to photoperiod than the temporal .... or am I looking at them wrong?

**Comment by cchambe12** [comment]
@lizzieinvancouver
That’s what I’m seeing too but I may have done something wrong, we’ll see if it passes the Ailene and Nacho test.

**Comment by AileneKane** [comment]
Great work @cchambe12! I have a few questions about it- I put some comments in the code, but maybe we can talk about it at our next meeting and/or set up a time to skype.  I think I would have calculated the OSPREE shifts differently. Also, I think this figure would be better suited for the photoperiod paper, rather than the limiting cues paper, as the label says, given that all the axes are related to photoperiod. It would be great to have something like this for the limiting cues paper, but i think we would need to add climate data for the range of each species, so that we can calculate chilling and forcing in each grid cell. Doable, with our daily climate data, but will require some extra work so perhaps we can discuss if its worth it!

**Comment by cchambe12** [comment]
@AileneKane oh right yeah I think I messed the label up!! Definitely thought it was supposed to be for the photoperiod paper too. And yes, excellent, I was most nervous about how I calculated the shifts in OSPREE so I'd be happy to hear your ideas!

**Comment by lizzieinvancouver** [comment]
@cchambe12  Next tasks!
- Look at the extreme points and what causes them (ask Isabelle about them once you check it)
- Try showing all the points
- Make 3D versions in same colors and way as 2D

**Comment by cchambe12** [comment]
1.  I made a map to show why there seems to be extremes - Fagus_projected_map.pdf

2. I added jitter points to map code so hopefully this helps! - 2D_fagus_actual.pdf & 2D_quercus_actual.pdf

3. Made 3D versions - FAGSYL.png & QUEROB.png

**Comment by cchambe12** [comment]
@cchambe12 scale the OSPREE data for days to budburst and adjust using first Phenofit datapoint

**Comment by cchambe12** [comment]
I checked out those 15 data points that had the significantly later budburst times than the current days to budburst and found...

12 out of the 15 data points had photoperiods that were 5-8 hours shorter than was biologically possible.

The last three data points:
2 data points either had very low or no chilling and the last data point had 61.115 chill portions (pretty middle of the road, slightly lower) and 18degC forcing... hmmm..

**Comment by AileneKane** [comment]
Interesting! Not sure how to explain that last datapoint...but the 12/15 now make sense...
