### ISSUE TITLE
apples: do they affect model output much?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#181]

**Comment by cchambe12** [comment]
I removed apples from the brms model because it was just easier coding (I can do the main rstan model as well if we deem it's necessary!)

Model output with apples:
#a 94.7, f:-1.83,p:-1.4,c:-6.97. f*p0.01,c*p=.11, f*c=15 sigma 14.59

Model output without apples:
# a: 95.50; f: -1.92; p: -1.46; c: -7.02; fp: 0.01; fc: 0.15; pc: 0.11; sigma: 14.96

**Comment by lizzieinvancouver** [comment]
Apples are not a big deal! We can easily rm them from the models in a supp as needed
