### ISSUE TITLE
check Picea abies

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#191]
_Picea abies_ is the most widely planted outside its range ... check its range vs where our OSPREE data.

**Comment by dbuona** [comment]
It turns out the Pinus sylvestris is the most widely planted species outside of its native range not Picea abies... :\.... BUT.... a relatively large study (Worrall67) looked Picea abies in North America (it's Native to Europe). So basically 18% of our Picea abies data in bb analysis comes from outside of the species native range.

Perhaps we could try running the model excluding Worrall '67 to see if the the species behaves differently.
Relevant map and code can be found in the bb_analysis/scratch folder.

**Comment by lizzieinvancouver** [comment]
Work on rm Worral67

**Comment by lizzieinvancouver** [comment]
rm 29 rows ... made the value MORE positive. 
The old mean was 0.5 (-0.6 to 1.6, 2.5% and 97.5%) and now it's 2.6 (-2.3 to 7.4). So I think we should double-check what the Picea abies studies found. 

**We should also check my models_stan_plotting.R code is lining up the species correctly!** Why is unique(bb.stan$complex.wname) giving 42 names, but we only have 38 species in the models?

Note that I didn't save the code, I used models_stan.R code. Here's some of it:

```
bb.stan <- subset(bb.stan, datasetID!="worrall67")

> datalist.bb <- with(bb.stan, 
+                     list(y = resp, 
+                          chill = chill.z, 
+                          force = force.z, 
+                          photo = photo.z,
+                          sp = complex,
+                          N = nrow(bb.stan),
+                          n_sp = length(unique(bb.stan$complex))
+                     )
+ )
> try  = stan('stan/winternosp_2level.stan', data = datalist.bb,
+                iter = 4000, warmup=2500) 
trysum <- summary(try)$summary
trysum["b_photo[20]",]
```

**Comment by dbuona** [comment]
Picea problems:
1. gomery15 is complete wrong, and should probably be thrown out. It is, in actuality, a reciprocal transplant study with no cues manipulated. It seem like photoperiod and field sample date were rather arbitrarily assigned. This is the one that is dragging our results because a 1 hour increase in photoperiod corresponds to a ~30 day delay in our data, which is, again, totally made up and whack.
Other problems:
Partanen01 and 98 are testing the effects of increasing and decreasing photoperiods on budburst, however, we have them coded as constant (the starting point). These seems wrong, but complicated to fix. Maybe we decided something about this earlier in the project?

Summary: No more Gomory!

**Comment by lizzieinvancouver** [comment]
@dbuona We actually do not throw studies out just because they are reciprocal transplants; if they meet our search criteria and they manipulate cues somehow they stay in (this is an issue with every meta-analysis I have done, you usually end up touching on some much bigger/different literature but it can be hard to define how/why to throw out such studies so we don’t generally and in this case a simple reciprocal transplant study should be okay IMHO; I am not sure how we could justify it as something totally different). Whatever decisions we make for gomory15 have to be equally applied across all studies.

Further, I looked at the base format of gomory15 and see the temp and photoperiod listed as ambient. This means we must have pulled local photoperiod and local climate, and taken the mean. The dates given are taken from Table 2, they seem to take the first scoring date for each as a field sample date, so I think this should work okay functionally — no?

Where gomory15 *does actually seem different is in the other.treatment column* where the double-reciprocal part of the transplant shows up (e.g., ‘first year trt= warm, second year trt = warm’) so I think we should look more into this, which is a already flagged issue for our analyses. 

@cchambe12  Could you check out Partanen01 and 98 and see when/why photoperiod edits happened? I think if Dan’s read is correct we should take the mean, not the starting value but another set of eyes would be great. 

Could you also check if gomory15 was a photoperiod we estimated and double-check our estimation if so?

@AileneKane Could you confirm we calculate the daily climate data to get the temperature data for gomory15?

**Comment by cchambe12** [comment]
Partanen98: I only fixed the 'ambient' inputs it seems because the other values didn't show up as an issue, the ones I fixed follow Dan's suggestion but the other cells need to be tweaked. I can work on that! As for Partanen01, it was not cleaned anywhere for photoperiod so it must have been filled out entirely when originally inputted. I will check that out as well! I agree with Dan, they should have the photoperiod at budburst not the photoperiod at the beginning of the experiment.

**Comment by lizzieinvancouver** [comment]
**RECAP:** At least two studies are weird here: gomory15 and Partanen98. These two really do show that longer photoperiod leads to later budburst, but with a lot of complexities! And both of these show up HEAVY on datapoints because they have lots of ambient or ramped treatments, so we need to work on this. 

Here's code to use with bb.stan data to look at this:
```
# Quick look at PICABI
picabi <- subset(bb.stan, complex.wname=="Picea_abies")
unique(picabi$datasetID)
ggplot(picabi, aes(photo, resp, color=datasetID)) + geom_point() +
    geom_smooth(method = "lm", fill = NA)
```

**Comment by lizzieinvancouver** [comment]
@AileneKane Hi Ailene! Since you're in charge of checking partanen98 can you let us know here if the photo treatments are correct (that is, some are truly ambient and others are ramped)?

**Comment by lizzieinvancouver** [comment]
@lizzieinvancouver Update this!

**Comment by lizzieinvancouver** [comment]
As part of cross checking all the papers I looked at the PICABI studies and they are weird... Here are some notes:

> partanen01_exp1: This is probably why we have weird results for Picea abies! They compare lengthening photoperiod (starting at 6 hours and getting LONGER); shortening photoperiod (starting at 16 h and getting SHORTER) and constant and they find that SHORTENING photoperiod advances budburst. Which is just WEIRD. (From abstract and checked table 1 to confirm): 

> The timing of bud burst was examined. In all plants, shortening photoperiod treatment seemed to promote bud burst compared with other treatments. 

See also, partanen98 (opposite effects)... these studie shave the species: 
`[1] "basler12"   "basler14"   "laube14a"   "partanen01" "partanen98" "zohner16"`

basler14, basler12 shows only very small photo effects (but normal: short delays) so I think the partanen work may drive things ... Laube finds 389/334 days for 8/16 hr (Table 1), did not check Zohner.
