### ISSUE TITLE
check forcetemp

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#198]
from issue #196 
`Side question that i want to make sure to ask: do we use the avg_bbtemp column at all? It doesn't look like it from the model code that i have checked, but perhaps i'm missing it. i think there are some studies with NAs for forcetemp that we have data in this column...`

@cchambe12:  can you check? I thought we used this when forcetemp was empty or NA in the bb_cleaning....

**Comment by lizzieinvancouver** [comment]
@AileneKane @cchambe12 After looking at Morin10 I wanted to pick up this issue (note that in morin10 it has 'ambient' in the forcetemp column but this doesn't turn into a calculated value in the BBwithchill file). Can one of you head up efforts to see what happened with updating forcetemp with extracted gridded climate data when it was set to ambient (or ambient + 1 etc.)?

At this point I think we do NOT need to actually do this, but it would be good to check if we have half done it or such (for example, maybe we did not do it for Morin10 since there is a field sample date??)? And to leave ourselves notes about how to implement this if we did want to do it.

**Comment by AileneKane** [comment]
@lizzieinvancouver @cchambe12 this type of thing gets done in bb_daily_dataprep.R However, I do not remember doing anything for Morin10, and I'm not sure why. 

This daily data then gets used to calculate average forcing temps through till the bb date in clean_ambientforcingfromdailydata.R in bb_cleanmergeall.R. However, I believe it is the case that we do not use this averaged daily data (which is appended in a column that i think is called "avg_bbtemp") in our model-fitting.

**Comment by lizzieinvancouver** [comment]
@AileneKane @cchambe12 I think we must add it somewhere under some rules ... I just noticed for sanzperez10 we have some the ambient values changed to actual numbers but not all of them. 

Could it be that this only works when we had info to calculate chilling? (Though on quick glance this does not make sense for sanzperez10.)

**Comment by cchambe12** [comment]
@AileneKane @lizzieinvancouver 
I think I discovered the problem! In bb_analysis/cleaning/clean_ambientforcing.R I changed a handful of studies (including Morin10 and sanzperez10) that were ambient and estimated the forcing temperature at bud burst based on figures in the papers. I can definitely remove these lines of code so that they are fixed in clean_ambientforcingfromdailydata.R!

**Comment by lizzieinvancouver** [comment]
@cchambe12 (cc @AileneKane) 

Ah! That makes sense. So I think we have a few things to do:
(1) We should only change ambient in clean_ambientforcing.R if the paper gives us a clear good estimate to use. If not, see (3)....
(2) We should also add a force_type column in clean_ambientforcing.R for exp or amb.
(3) Move any code you have in clean_ambientforcing.R into clean_ambientforcingfromdailyclimate.R but maybe just add at the end within if(FALSE){} ? As we need to decide what to do about forcing .... and I think that code would need work. 

**Note to all of us:** clean_ambientforcingfromdailyclimate.R says at top "This file is unfinished -- need to explicitly incorporate ambient and ambient +1, +4, etc."

**Comment by AileneKane** [comment]
in regard to the Note above, the explicit incorporation of ambient and ambient +1, etc happens in bb_daily_dataprep.R, which creates the daily climate data files used in clean_ambientforcingfromdailyclimate.R. Should I remove the sentence above, as it may be confusing?

**Comment by lizzieinvancouver** [comment]
@cchambe12 @AileneKane 
Next steps as I recall (please add what I forgot):

- Ailene should adjust notes in clean_ambientforcingfromdailyclimate.R as noted above 
- Cat will work on forcetemp_type column, including multiple types of ambient (amb_frompaper, amb maybe?) 
- Cat, will review  clean_ambientforcing.R and clean_ambientforcingfromdailyclimate.R; Move any code we have in clean_ambientforcing.R into clean_ambientforcingfromdailyclimate.R if appropriate
- Cat will work on adding notes to clean_ambientforcingfromdailyclimate.R and clean_ambientforcing.R detailing what each does and checking that we don't use clean_ambientforcingfromdailyclimate.R at all yet. We should make a clear note in this file that we DO NOT currently use it and where it is at if we do want to use it. 
- Make notes as appropriate in bbcleaning_README.txt also.

Once done pass to Lizzie to check ... 

... What am I forgetting?

**Comment by cchambe12** [comment]
@AileneKane  @lizzieinvancouver I think I'm all done with this! Please let me know if something looks wonky! 

I added a force_type that is `not enough info'. This is for the skuterud paper that has `mean of 9, 12, 15' in the force temp column. We weren't able to determine which of the three temperatures they used for each observation due to the ambiguity of the figure. I also have `not enough info' for some of the basler12 observations which currently has `meandaily' in the force temp column. They ramped the force temp but I couldn't calculate it for the thermal time observations. The rest of the basler12 experiment is daystobudburst so I was able to calculate those forcing temperatures and that force_type should be labeled as `ramped'.

**Comment by lizzieinvancouver** [comment]
@cchambe12 I think it looks great! I made a few formatting tweaks but I think we can close this when you're ready.
