### ISSUE TITLE
make a new column for type of photoperiod

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#208]
Make new column that explains what sort of info is in the 'photoperiod_day' column of clean BB data...
I made these categories up, change as you see fit!
exp: experimental photoperiod with set day/night lengths that are constant across experiment
amb: ambient photoperiod
ramped: ramped photoperiod (or similar?)
none: no photo info (just leave empty I think?) 
... there are also a few where the photoperiodicity is different than the thermoperiodicity but I can't recall if we already handle those.

**Comment by lizzieinvancouver** [comment]
@cchambe12 I just noticed that for "partanen01" two of the three photoperiod treatments are RAMPED. It's noted in "other.treatment" ... so we should be sure to check this column for our photoperiod work!

**Comment by cchambe12** [comment]
I think this is done!  I added the four types and the break down is...

   amb      exp        none     ramped 
  1346     5875       100         49

**Comment by lizzieinvancouver** [comment]
@cchambe12 
And one more query in addition to the above! There are some labelled "none" that have photoperiod ... could you take a quick look at those?

**Comment by cchambe12** [comment]
@lizzieinvancouver for two studies I imputed data using the geosphere package but there was no mention of photoperiod in the paper so I labelled them as "none". Should I remove those imputations? 

And... Yes you are right about Basler12 & 14! Your code looks good but it did not show up in my version of ospree_clean.csv... maybe a new version of ospree_clean.csv needs to be updated and pushed to the repo? Or we probably want to wait after all the cleaning is done! Anyways, I will update my code in bb_analysis/cleaning/clean_photoperiod.R (should this code be in the original cleaning folder instead??) so that the baslers are fixed. Also, the actual data does not reflect the ramping, should I clean the photoperiod data?

**Comment by lizzieinvancouver** [comment]
@cchambe12 
Can you pull and check your ospree_clean.csv again? I see the ramped_photoperiod in other.treatment in mine (note for basler14 some of the photoperiods are NOT ramped, as best I understood it so you'll see it for only some treatments). I am not sure if this will carry through to the rest of the OSPREE data as Ailene has to re-run the chilling code for that.

As for the two 'none' photoperiods, how are these papers different than ambient? Is it just that they don't even say that they used ambient photoperiod or such? Or can you pretty much tell that they did (e.g., Morin10 probably doesn't say but the plants are outside in a field warming experiment so it pretty much has to be ambient).

**Comment by cchambe12** [comment]
@lizzieinvancouver Yes, I see ramped_photoperiod in ospree_clean.csv but not in ospree_clean_withchill.csv and it looks good!

As for `none', yes these studies don't even specify if they were ambient or otherwise but was likely ambient.

**Comment by cchambe12** [comment]
@lizzieinvancouver Update with notes on what each category means, check the new ramped photoperiods show up... and close issue after all that is okay.

**Comment by cchambe12** [comment]
I added notes to the bbcleaning_README.txt and to the clean_photoperiod.R script and I checked the ramped photoperiods and all seems good!

**Comment by lizzieinvancouver** [comment]
@cchambe12 Looks great! I am closing this one.
