### ISSUE TITLE
paper check: sanzperez09

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#209]
@AileneKane Since you entered sanzperez09, can you take a double look at it for me? I am not sure why forcetmp_night was entered as ambient ....

**Comment by AileneKane** [comment]
I carefully reread the paper, and I agree that there is no mention of night temperatures being ambient. i am not sure why it was entered that way. after rereading the paper, i would assume that night temperatures were the same as day temperatures. do you want me to clean this? So sorry about this mistake! I guess that's why we're doing this though....

**Comment by AileneKane** [comment]
a note to myself (assuming that i am the one who cleans this): for this study, and any others changed from "ambient" to something else- check the "clean_ambientforcing" and "clean_ambientforcingfromdailyclimate" files to make sure that any lines calculating the ambient forcing data are removed for this study.

**Comment by lizzieinvancouver** [comment]
@AileneKane I just changed it, see commit a0435d40e8a08472deed218c61713e6dbfeb83ef ... I checked and did not see it in the other clean forcing files, I think probably because it was only in the forcetemp_night column.
