### ISSUE TITLE
discuss: covar(slopes, intercepts)

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#253]
Should we add covar(intercepts, slopes) to OSPREE models?

**Comment by lizzieinvancouver** [comment]
@AileneKane ... will plot slopes versus intercepts on centered model.

**Comment by AileneKane** [comment]
i plotted the intercepts vs slopes from the centered model [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/slopes_v_ints_points.pdf). If you want to see each species' line plotted its [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/figures/slopes_v_ints_lines.pdf).

**Comment by AileneKane** [comment]
I'm not sure that we need to allow them to be correlated in our model- I'm still learning about this- but I would be curious if it would affect our estimates much (I expect that it would not). I found these articles helpful in thinking about this: http://www.stat.columbia.edu/~gelman/research/published/chung_cov_matrices.pdf, http://jakewestfall.org/misc/SorensenEtAl.pdf, https://mc-stan.org/docs/2_18/stan-users-guide/multivariate-hierarchical-priors-section.html

**Comment by AileneKane** [comment]
@AileneKane will fit models in rstanarm (and maybe brms) and read about their approach to covar(slopes,ints) to see how model estimates change with this included.

**Comment by AileneKane** [comment]
I compared our stan model with utah and centered predictors to rstanarm and brms models: chilling is a bit higher for our stan model than the other two, but otherwise they are all quite similar. 
![image](https://user-images.githubusercontent.com/9097640/57236832-ba42bb80-6fda-11e9-924a-db90581feae3.png)
code is here: https://github.com/lizzieinvancouver/ospree/blob/master/analyses/bb_analysis/models_comp_stanarm_brms.R

**Comment by lizzieinvancouver** [comment]
Cool! I feel like we could close this if you want?
