### ISSUE TITLE
Total chilling estimates not quite done

### ISSUE THREAD

**Issue by AileneKane** [lizzieinvancouver/ospree#28]
We need to add columns for provenance latitude and longitude to the field chilling calculation table generated in Field_Exp_Chilling_Calc.R. (This should remove the merging problem described below, if we merge with these columns as well as the ID_fieldsample date column.) I have added the code in comments in the R script, but could not run it without the climate data.
Merging of fieldchilling into ospree_clean1.csv didn't work perfectly- generating 549 extra rows of data ...this needs to be fixed, but a draft file of ospree_clean1_withchill is available  here: https://github.com/danfbflynn/ospree/blob/master/input/ospree_clean1_withchill.csv

**Comment by danfbflynn** [comment]
Partly dealt with by non-woody studies in chillcalcs; still need to work on this

**Comment by AileneKane** [comment]
we have now added the provenance latitude and longitude!

**Comment by AileneKane** [comment]
i have found the duplicate rows! they located i in the "fieldchillcalcslatlong.csv" file and are generated at some point in the process of pulling climate data and/or estimating chilling for each lat/long. I cannot investigate this further without access to the climate data on the external hard drive, so I can work on this at the retreat or in working with Cat on Monday Jan 30 or Tuesday Jan 31. (Cat, I'll email you about the possibility of you working with me on this!)

**Comment by AileneKane** [comment]
This is done! Only thing left is to cleaning non-numeric chilling treatments and re-run code to estimate total chilling

**Comment by lizzieinvancouver** [comment]
Notes from Lizzie and Ailene ... now that Lizzie has this running on her machine she re-ran it and Ailene and her checked the differences. Here's the relevant bit from Ailene's email on 21 Mar 2017:

I looked at the changes you noted, as well as all other changes that I could see. Most are due to the fact that chilling calculations are now done using growing lat/long (not provancne lat/long), if that is listed. One change (pagter15) is because I cleaned the lat/long. The following studies were those that changed between the two versions:

heide93: 
hawkins12
pagter15: lat/long cleaned by me
partenen01: 
skre08: 
calme94: 
nienstaedt66-
schnabel87
webb78
yazdaniha64
spann04
sonsteby14
skuterud94
Sanz-Perez09

So, they all make sense to me!

And the email from Lizzie was:
On Mar 20, 2017, at 4:38 PM, Wolkovich, Elizabeth M <wolkovich@fas.harvard.edu> wrote:

Hi Ailene!

No more errors! Just some warnings about coercing columns close to the end. Sound good?

I would like to make sure we're okay with what changed in output/fieldchillcalcslatlong.csv. I attached the current version and one from Feb 1's commit. You should have a program called FileMerge on your mac (mine is buried in Xcode/contents/applications bit Spotlight search finds it quickly) that makes it easy to compare these files. Here are some of the differences I noted:

heide93 -- many new rows added
changes to pagter15 and partenen01
losses in skre08, calme94, hawkins12

Could you possibly look when you have time and see if these make sense to you and look okay?

I also compared the full ospree_clean_withchill.csv that I just pushed from the one we had on github before (see the pdf, the left side -- datb4 -- is older data, the right side is current).

If you don't have time or interest in this feel free to bounce it back to me ....
