### ISSUE TITLE
adjust the gridcell weighting

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#387]
Likely not to make a big difference, but would be good to fix before we meet with Ben again. @MoralesCastilla @cchambe12 can you work on this?

From Nacho's email:

> We are not weighting / nor correcting by cell size (area), but that could be easily done (the function ‘area()’ within the raster package generates a raster file with the same specifications of the raster you put inside the function, and values equal the area size of each grid cell. Then it would just be a matter of correcting by that value. Nevertheless, doing so is not going to change (much) nor is driving the strong geographic patterns in the climate variables. This is, it can modify the figures slightly but is not going to change the large differences we see between EU and Nam, nor the latitudinal/longitudinal differences within continents.

**Comment by cchambe12** [comment]
@MoralesCastilla I think I found a quick and easy way to adjust for this! 

If we add, `weights=TRUE' and `normalizeWeights=FALSE' to any extract() function it seems to be doing what we want it to do. 

Example:
pixels.sps.i<-unique(sort(unlist(raster::extract(ras.numpixels,spsshapeproj, weights=TRUE, normalizeWeights=FALSE))))

I have updated all files for North America

**Comment by MoralesCastilla** [comment]
@cchambe12 

Hi Cat, I'm not sure this is exactly what we wanted, but perhaps is (I'm going to check it). This fix seems good to adjust for the amount of an overlapping raster cell with a polygon for which we are extracting the data. We had not done this before, and so it sure will be a good fix to add instead of assuming that all overlapping cells should be included fully (what our previous approach does). I'm not sure this will make a big difference, but any estimates will be more precise and so it is complementary to what we were doing previously, nice catch! 

However, I'm doubtful as to whether this deals with the original Ben's concern: the fact that unless you use an equal-area projection (e.g. Albers or Behrmann) in the maps, raster cells will not have the same size because the earth is round (e.g. a pixel in northern Canada is larger than a pixel in Florida). I think what Ben wanted was to make sure that the latitudinal climate patterns we mapped were not due to this fact. So, I think we still need to follow Ben's proposed steps (get pixel areas, multiply by env., sum all, and get an average)... don't we?

**Comment by MoralesCastilla** [comment]
Dear rangers,
@dbuona @cchambe12 @lizzieinvancouver 

I was supposed to get back to Dan with weighted results for Europe, but in dealing with Cat's code I have come across my concern/comment above. 

I think what Ben meant was that we should weight pixels by their size. Instead we could weight in by the size of each subpolygon in which each species range is subdivided (this is what Cat's code does, if I understood correctly), but am not sure that is what we want (or I'm not sure of the rationale for it). If you confirm that so is what we want I can readily update and upload results for EU species. 

If instead, what we want is to weight by pixel size, I started a piece of code (below Cat's, in ) that does the job at weighting pixel size, but I got stuck trying to apply it to weighted standard deviations with aggregate. I can write a loop to do so, but it is going to take long to compute, so perhaps you have insights as to how to correct it. Please see the new code at: 

analyses/ranges/Get_range_ospree_full_weights.R

Sorry to come back to this issue, but it could have a noticeable effect on results.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Hi Nacho! Thanks for working on this (and apologies I missed your earlier comment, I found this and that one in my trash -- argh! And I cannot figure out why ... problem for another day). Quickly..

(1) Yes, you are correct. My understanding is Ben wants us to correct for pixel size (bigger towards poles).
(2) Could we not use another projection and go from there? I know nothing about maps so assume this is not possible? If not, we could ask Ben for any ideas. (If he doesn't have any we could just correct it for a few analyses and check it doesn't matter maybe?)

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver Hi Lizzie!

(1) Quite a relief! (I realized pixels are actually smaller towards the poles when using geographic projections just because in a sphere, meridians get closer to each other as they approach the poles... counterintuitive, I know!).

(2) This would be doable using an equal-area projection (e.g. Behrmann, Albers; in these, each pixel has exactly the same size and thus avoids the need to weight values... I totally should have thought about this before). I guess using this approach would involve transforming the projections of the rasters and of the shapefiles (on the fly, not sure how long that will add to processing times), and then running our code as is. I can give this a try with one example species to get an idea of how long will it take.

**Comment by cchambe12** [comment]
@lizzieinvancouver @MoralesCastilla The way Ben framed it, it seemed so simple! 

Here were his instructions:
For the area weighted average across grid cells, this is how I usually do it: 

1. Calculate the area for each grid cell (sounds like you have a function for this)
2. Multiply each grid cell value (e.g., GDDs) by the area, and then sum this across ALL grid cells
3. Sum just the grid cell areas across all grid cells
4. Area weighted average = (2)/(3)
 
So I tried adding that in the code by using the area() function in the raster library... 
`### Now we need to get the area weighted average across grid cells. See Issue #387
      sps.area <- area(spsshapeproj) / 10000 ### step 1
    
      means.years <- aggregate(sps.i[,-11],by=list(year = sps.i$year), FUN = function(x) sum(mean(x, na.rm=TRUE)*sps.area)/sum(sps.area))`

This did not change my results very much at all but I think the USDA shapefiles are in Albers already so that might be why.

**Comment by MoralesCastilla** [comment]
@cchambe12 @lizzieinvancouver 

Hi Cat! I saw your code (which is great since you manage to compute weighted sds, I couldn't), and the thing I don't get from it is that the function area is not applied to the raster (and thus to grid cells) but to the shapefile `spsshapeproj`, so that the resulting `sps.area` object has as many elements as the number of features (or subpolygons) in the shapefile (e.g. 28 for Abies alba in EU, instead of 368 pixels comprised by this species' range). I may be totally wrong and have missed something, but this is not exactly equivalent to step 1, in Ben's list, is it? 

My proposed way around it do so you would be (in several lines of the new code):

```
ras.areas <- area(tmin[[1]]) ## this step generates a raster file with vales for each pixel corresponding to its area

values(ras.areas) <- (values(ras.areas) - min(values(ras.areas),na.rm=T))/
  (max(values(ras.areas),na.rm=T)-min(values(ras.areas),na.rm=T)) ## this step (optional) would re-scale pixel's area values to range between 0 and 1, but it is easy to do 1-2 by adding 1.

## then you'd need to add a column with either areas or rescaled areas:
sps.1$weights <- extract(ras.areas,sps.1[,1:2])
```
Please let me know if this makes sense or I missed something relevant.

**Comment by cchambe12** [comment]
@MoralesCastilla Hi Nacho, sorry this is so delayed! This looks right to me and makes a lot more sense for sure. I will play around with this for the North American species and we can go from there.

**Comment by cchambe12** [comment]
@MoralesCastilla @lizzieinvancouver @dbuona Sorry for the delay but I _think_ and I _hope_ this is finally done for the North American species

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @cchambe12 I have run the code for EU sps and generated a new file, with the synthesis of climate data:
`output/Synthesis_climate_EUspsw.csv`
I have not checked it against the previous `output/Synthesis_climate_EUsps.csv` sps by species but overall data across species are very highly correlated (r>0.99). Cat, since you have done this with NAm species, perhaps you can double check these new data?

**Comment by dbuona** [comment]
@MoralesCastilla Thank you so much for doing this! I know these data are beastly and I appreciate your heroic efforts with them.
I'll start running models with these data but @cchambe12 can you give Nacho's code a quick check to make sure we are "ready to rumble"?

**Comment by cchambe12** [comment]
@MoralesCastilla Thanks, Nacho! The code looks great to me. Let's see how things change in the models.

**Comment by cchambe12** [comment]
Seems like we wrapped this up! Great work team!
