### ISSUE TITLE
finalize  Fig1_noblues_densities.png

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#399]
![Fig1_noblues_densities](https://user-images.githubusercontent.com/2153556/107996217-b5bf7b00-6f94-11eb-8d27-366a93d95221.png)

@AileneKane  asked last year for us to "describe somehow that the color of the dots relates to the temperatures in the histogram" -- can we add a color bar and/or just some text to explain?

Also, can you draft up SOME quick methods for your part of this?

Finally, do you have a file name you used for the OSPREE data in the figure? That might help ME track down the rest of the questions and write up the methods for that ... 

Now, @lizzieinvancouver needs to deal with ...
- XX in ... and forcing (B,D) treatments across XX studies ...
- It's not quite clear to me what "temperatures relevant to chilling...and forcing"
-  "Is the histogram showing changes in temperature or temperature? The axis label says temperature but the figure legend says changes in temperature. If it is temperature" 
Must find the R file we used.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Okay, I figured out where my code is (studydesignplots.R) so I need from you:

1. Are the dots and histogram colors showing the same thing? If so, the histogram x label should be changed (Maybe "Change deg C" or such?).
2. Where does the climate projection data come from?
3. What temperature windows are min and max calculated for?

I checked issue #174 and did not see this info there, but could have missed it.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver Wow, it's been a long time since I worked on this!

1. dots and histograms show the same thing, so yes, I will change the inset x-labels for the histograms.
2. climate data comes from the CMIP5, the same version we used for the winegrape paper (RCP8.5), and specifically one of the 30 simulations: 'GCM.07.Tmin1950-2005.nc', 'GCM.07.Tmin2081-2100.nc', 'GCM.07.Tmax1950-2005.nc', 'GCM.07.Tmax2081-2100.nc'. 
3. I'm trying to make sense of the code. It seems like temperature windows are DOY 1 to DOY 61 for mins, but I'm figuring out what's for maxs. The code is in [here](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/Plotting_spring_cues.R).

I will run it tomorrow and get back to you with any findings.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Thanks Nacho! I'll work on updating the text and work on the supplement soon. I too cannot figure out the code (and I am sorry I did not keep better notes on this).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Looks good! Thank you! Any insights into the temperature windows? (I am working on an updated manuscript draft.) If you're low on time and can tell me what temperature to reference (is it EOBS?) I can try to run the code.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver I have now gone through the code more thoroughly now and figured out what it did. 

The temperature windows to calculate minimum and maximum temperatures for both the past and the future, encompass the 60 days prior to the phenological event in PEP75 at each site and for each year. So the code extracts climate data for 61 days, 60 days preceeding the event and the date of the predicted phenology. The temporal window is the same for minimum and maximum temperatures. Please let me know if this helps or you need more details.

The relevant bit of code I had missed before is:

`dates.matrix=t(apply(as.data.frame(dat.days),1,function(x){return(seq(x-60,x,1))}))`

**Comment by lizzieinvancouver** [comment]
Some old notes on this in issue #174 ... but hoping we're done on this for now. Thank you @MoralesCastilla !
