### ISSUE TITLE
help with limitingcues supp

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#407]
@AileneKane If you have a few minutes could you review the xtable I have added to the limiting cues supp? Line 104 onward of [this code](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/docs/limitingcues/limitingcues_supp.Rnw). I copied your nice code for this sort of table, but I feel crazy as it prints out in the WRONG order for the dataset column. I keep looking and cannot figure out why ... any quick look would be appreciated. Maybe we could look at it together for 10 minutes tomorrow?

It sources [this file](https://github.com/lizzieinvancouver/ospree/blob/bbculdesac/analyses/limitingcues/reftable_limitingcues.R)
When I run this in R though it prints out correctly (sorted that is).

**Comment by AileneKane** [comment]
hmm...I have had some trouble in the past with xtable doing weird things with my datadrames. HAve you tried saving as a table instead of a dataframe? (They suggest that here https://stackoverflow.com/questions/3661451/sorting-a-table-for-latex-output-with-xtable) Also, is it due to a quick in longtable? (Have you tried removing that? I think I ran into problems with that before..)

**Comment by AileneKane** [comment]
@lizzieinvancouver I added a new test supp file with just the table you made- it looks correct when i compile it. I hope it works for you!
https://github.com/lizzieinvancouver/ospree/commit/03bb04e7c94a9f76122294619827d5a7068fd8b0

**Comment by lizzieinvancouver** [comment]
@AileneKane Thank you! Oddly when I printed it the datasetIDs printed as numbers ... but having the test file let play around easier and I figured out the issue! I think ... my computer was putting the two dataset IDs with capital letters FIRST ... so in R it sorted correctly, but somehow not in tex. Anyway, it is fixed! Thank you!
