### ISSUE TITLE
update figure 1

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#430]
@AileneKane We discussed simplifying this figure so a core message was more clear.  My notes seem to be from 22 September, but I did not take good notes on how we wanted to change the figure. Maybe you did? If not (or either way) I am happy to discuss. I am hoping to have a new draft (with updated figure) of the ms to send around in the next 2 weeks ... let me know what's feasible (I realize it is a holiday in America). Thanks!

**Comment by AileneKane** [comment]
ok @lizzieinvancouver  and @MoralesCastilla I have made a first pass at a simpler, 3-panel figure (getting rid of panels B, E and F from the previous version) [here](https://github.com/lizzieinvancouver/ospree/blob/3f597f159a6ed5c83c7eca5156f31feb110dd09b/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_3panels.pdf). We could put the threshold responses in a supplemental figure if we really want to, but I don't think they add much. Are there other messages we want from this figure,  beyond that nonlinearaties can results from correlated shifts in cues? If so, we may want to add additional things to this figure. If not, or when we settle on a final simplified version, perhaps @MoralesCastilla could make it prettier, as he did before?
Here is a possible modified legend:
'Interactions can produce nonlinearities, even in simple linear models if there are correlated shifts in cues. Much research focuses on how warming increases forcing, but it may also alter other cues, including photoperiod experienced near the time of the event, which is expected to shorten, and chilling, which may either increase or decrease (A). Shifts in forcing alongside shifts in a second cue may produce non-linearities due to the interaction between cues (B-F showing the effect of: forcing-only in yellow, both cues without an interaction in lighter purple/blue, and both cues with an interaction in darker purple/blue). The overall change in budburst day predicted with warming depends on the sign of the second cue (positive in B, negative in C), as well as its strength (weak/strong). We show linear cues here, but cues may be threshold responses (Supp Fig).'

**Comment by lizzieinvancouver** [comment]
@AileneKane Wow! That was super fast. I like it! I think we could hold off on edits until you and @MoralesCastilla read a new draft ... right now I wonder if we want to stress the no interaction vs. interaction more and then additionally the correlated cues (that could just be done by @MoralesCastilla  making it prettier), but I think best if you wait to read it.

Thank you!

**Comment by lizzieinvancouver** [comment]
@AileneKane No rush, but can you check the mismatch between your labeling on the figure and the caption? B is negative and C is positive (as in the figure)?

**Comment by AileneKane** [comment]
@lizzieinvancouver Yes I apologize for my mistake- B is negative and C is positive, as in the figure.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Ailene asked, "Super small thing- should we make the letter type (cap vs lower case, ) or not) consistent across our figures?" ... could you possibly switch to lowercase (a), (b) etc. here and in Fig7_noblues_densities (fig 4) if easy. If not, no worries! We'll likely have to chance for whatever journal to all lowercase or all uppercase and could wait for that time.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane I have made a couple minor tweaks to the [figure](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/limitingcues/figures/intxnsims2021photoaltwithchill_3panels_sm.pdf). Let me know any other changes that you'd like to.

Changes to Fig 4 are [here](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/limitingcues/figures/Fig7_limcues_noblues_def.png).

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla and @AileneKane Thank you!
