### ISSUE TITLE
Whatever happened with multiresp.R?

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/ospree#95]
We were supposed to develop code to deal with studies where we extracted multiple response variables (e.g., we extracted daystobudburst, thermaltime and percbudburst ... see heide93 or ghelardini10). I think multiresp.R was a start ... but it should be completed and moved to bb_analysis/cleaning ...?

**Comment by AileneKane** [comment]
Yes, I started on this with multiresp.R but did not have time to finish it at the retreat, and was unclear on what happened with it in the end. At the time, we were concerned with dealing with those studies that had multiple response variables and also used either days to budburst or percent budburst. At that time, there were only 3 studies for which there are multiple response variables and days to budburst, and only one study that  had multiple response variables and used percenty budburst. 
But we stil do need to deal with these studies.

**Comment by MoralesCastilla** [comment]
Hi Lizzie, Ailene, 

This issue was sort of duplicated (#81). I worked on multiresp.R (see my comment to issue #81 below). I would just need one of you to have a look at my edits to the code, and if we are all happy with it, we could close the issue.

_________

This is coming from issue #81:

I have now worked on multiresp.R. The code now does the following:

identifies studies with multiple responses. There are two types, studies containing "daystobudburst" or studies containing "percentbudburst" (only one of this second type). This was already been done by Ailene.

Identify which values (and their corresponding rows in the global dataset) are off (by 25%).

Remove the rows that are off from the global dataset. This bit is not activated as I would like you to have a look to ensure I'm not doing something weird.

**Comment by AileneKane** [comment]
Next step with this is to:
1)Fix/check multireponse column so that it is accurately accurately identifying the studies listed in issue #[81](url) by Lizzie

**Comment by AileneKane** [comment]
identify thermal time and days to budburst stiudies also

**Comment by AileneKane** [comment]
@lizzieinvancouver @MoralesCastilla @cchambe12 
I plan to move the multiresp.R file into the bb_cleanmergeall.R file as step 2. I will do this at 4:30pm today (June 6, 2017). Please let me know before then if there are any problems with that! After the move takes place, i will check the code and update the other code in bb_cleanmergeall.R  (or ask questions about it) as needed. Thank you!

**Comment by MoralesCastilla** [comment]
@AileneKane I have been re-checking multiresp and am not sure if I need to do something else there. It seems to work and it is in need of being activated (removing # sign in lines 51-52 and 96-97) if you and @lizzieinvancouver think it does what we want.

**Comment by AileneKane** [comment]
@MoralesCastilla We need to run through it and make sure that it works in conjunction with the other code in bb_analysis/cleaning. I will try to run through it once before lab meeting today, and then we can discuss questions and strategize for completion of this!

**Comment by AileneKane** [comment]
@MoralesCastilla I think I found the problem with the multiresp code. We need to update the multiresp code to use "d$multibothresp" in addition to  "d$multiresp" in Lines 15-17 (The difference between these
columns: multiresp: multiple original respvar which are now all one respvar.simple, multibothresp: multiple original respvar which each are a different respvar.simple) . I added line 17 because thermal time should also be included in this- it did not pull in any additional studies for the multiresp column but it may for the multibothresp column. 

Please let me know if you want me to work on making this change, instead of you!

**Comment by MoralesCastilla** [comment]
@AileneKane I have now made and pushed changes to include multibothresp in the code. I have ended finding a couple bugs that I have corrected too. However, we can't use <multibothresp> and <multiresp> simultaneously or then the code will not remove a single line. Thus, I have now started the code with:
<
target.multiresp<-c("multiresp","multibothresp")
i=2 #or 1
target.multiresp<-target.multiresp[i]
>
which sets in which classification <multibothresp> or <multiresp> do we want to base the trimming. The former removes ~2000 lines, while the latter removes ~ 130 lines.

Please @AileneKane have a look at it and we can decide which one to use.

**Comment by AileneKane** [comment]
@lizzieinvancouver @MoralesCastilla 
Ok, I realize this sounds crazy, but I’m thinking we may actually need a NEW multiresp column because i don’t think either multiresp or multibothresp does what we want….I think what we want the column to do is identify those studies that have multiple response variables entered  (e.g. percent bud burst and height; days to bud burst and percent bud burst). Neither of the current multi response columns do quite that. (See below for a reminder of what they do). 

One possibility that I have thought of is to make TWO new columns:
multi_respvar: identifies studies that have multiple response variables in the respvar column
multi_respvar..simple: identifies studies that have multiple response variables in the respvar.simple column


Sorry it has taken me so long to realize that this was the problem…i think Lizzie was on to this several months ago, but I didn’t quite understand the issue enough to advocate for her position. Now I have finally caught up!

Please let me know if you think these new columns are warranted, and, if so, I will add them to the respvar code. We can then use these two columns in the multiresp.R code (instead of the multiresp or multibothresp columns).

**Comment by MoralesCastilla** [comment]
@AileneKane @lizzieinvancouver 
I will go through it today and let you know when is fixed.

**Comment by MoralesCastilla** [comment]
@AileneKane @lizzieinvancouver 

Hi again, I think I figured out why it was not working. If you load directly `output/ospree_clean_withchill.csv`  as done in `bb_cleanmergeall.R` and that dataset has not been cleaned first by `cleanmergeall.R`, then the `clean_respvar.R` function has not been applied and the loaded dataset does not have the multi_respvar and multi_respvar.simple columns, which leads to empty subsets and the code to fail. 

I was tempted to correct this (so that whenever a subset is empty, the code just does nothing and keeps running, but I think is maybe best to have it failing if the columns that we actually want to clean aren't there. Please Ailene, try it after running the `clean_respvar.R` code on d. Let me know if it keeps on failing.

**Comment by AileneKane** [comment]
@MoralesCastilla @lizzieinvancouver 
Thanks for looking into this, Nacho. I'm still confused, though, because the cleanmergall.R code (which includes clean_respvar) should have already been run on the file ospree_clean_withchill.csv (the clean_respvar file creates ospree_clean, and then the chillmergeall.R file adds the chilling to it). I shouldn't have to run both of those files every time I want to use bb_cleanmergeall.R because I don't have access to the climate data (which is pulled in in chillmergall). 

For now, I can try using the ospree_clean.csv file (without chilling), I suppose, but I think we need to get the work flow order clear to make sure the code works properly and is not circular.

**Comment by MoralesCastilla** [comment]
@AileneKane @lizzieinvancouver 
I agree with you, it should not be necessary to run all the files everytime, I imagine the saved version of ospree_clean_withchill.csv was old and that is why it does not have the columns produced by `clean_respvar.R`. I can access the climate data from WeldShare, so I will save a newer version of ospree_clean_withchill.csv making sure it includes multi_respvar and multi_respvar.simple.

Getting there!!

**Comment by AileneKane** [comment]
Thank you, @MoralesCastilla ! When you do this, could you also make sure that an up-to date fieldclimate.RData file also gets pushed to the “output” folder?

i somehow missed your offer to do this, and just sent out an email to lizzie, you, and cat about this! sorry! i'll keep my eye out for when you're able to get to it!

**Comment by lizzieinvancouver** [comment]
Okay, just to reiterate, what I think we need to do here is:

(Aim 1) We need to deal with any data where multiresp=TRUE and make sure we are not using duplicate data 

(Aim 2) We need to deal with data where we have multiple forms of daystobudburst. Here is the order of what we want:

(1) Most want: daystobudburst (if we have this for a certain datasetID-study, we ignore the other response variables)
(2) thermaltime: I think we do not want this because we would have converted it if we could .... and thus it would be in daystobudburst
(3) percentbudburst with response.time filled in

**Comment by lizzieinvancouver** [comment]
For Aim 1: 
We only need to change things where it deals with budburst data: 

So for:
multiresp==TRUE & respvar.simple=="percentbudburst"
These look to me to be all one study: junttila12 I am not sure what to do (perhaps we can delete all entries where resp.var=="percentbudburst_dormancy"? Need to check study)

multiresp==TRUE & respvar.simple=="daystobudburst") gives even fewer entries .... all spiers74. In this study there was daysto50%budburst and daysto10percentbudburst. We should delete all daysto10percentbudburst (and thus leave daysto50%budburst).

We should note in the code that we are ignoring these other multresp==TRUE issues:
"growth"          "othernums"       "flowernumber"   "daystoflower"  

@cchambe12 Could you see if you can figure what percentbudburst_dormancy is in junttila12? I cannot figure it out!

**Comment by cchambe12** [comment]
@lizzieinvancouver Alright this is what I think may be going on...

It is indeed a daystobudburst experiment but the experiment is testing "the dormancy status" and "the induction and release of dormancy" so my guess is Beth wanted to specify the difference between the two experiments in the paper. The experiment with percentbudburst_dormancy was forcing bud burst after 4, 8, and 12 weeks of short photoperiod treatments and then 2, 4, and 8 weeks of chilling to test the status of dormancy and release of dormancy. 

I think we should change it to percentbudburst! This may end up with duplicate results though between Figure 1 and 2 but we have code to fix that right?

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
I have committed a new/corrected version of multresp `multiresp_corr.R` that deals with Aim 2 and does nothing for the Junttilla experiment. It still needs to address whatever we are doing for aim 1 and studies other than Junttilla. 

On another note, I'm updating the EU climate in WeldShare to re-run the chilling code and have an updated version of fieldclimate.RData and ospree_clean_withchill.csv.

 Moving forward...

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla 
Can you check my new lines 197-204? In particular make sure I did not delete any unique datasetID-exp-treatments in spiers74, I did not have time to check for this.

**Comment by lizzieinvancouver** [comment]
@AileneKane @MoralesCastilla 
Comments from above to revisit so we're ready to rock on 5 July ....

(May 24 with emoticon)
1) Fix/check multireponse column so that it is accurately accurately identifying the studies listed in issue #81 by Lizzie

(From June 8 with emoticon) 
target.multiresp<-c("multiresp","multibothresp")
i=2 #or 1
target.multiresp<-target.multiresp[i]

(From July 1 with emoticon) 
Can you check my new lines 197-204? In particular make sure I did not delete any unique datasetID-exp-treatments in spiers74, I did not have time to check for this.

And just generally pow-wow that the multiresp.R code does Aims 1 and 2 and does not do them twice or such ....

**Comment by AileneKane** [comment]
@lizzieinvancouver @MoralesCastilla 
I checked this and it seems to do the job- nice work guys!

the only question i have is about phestage- there are 6 studies that use this, and i think some of them are budburst? i noticed that this code is not activated in bb_cleanmergeall.R and I'm curious why.

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 

It seems that lines 197-204 work fine. 

I have now dealt with the target.multiresp bit so that it always select for "multiresp". I think we should probably remove the bits of code where `target.multiresp=multi_respvar.simple` to avoid confusions. If you give me the thumb's up I'll do that, and we may get nearer to closing this issue?

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla Removing bits of code where bits of code where target.multiresp=multi_respvar.simple sounds good to me! Let me know when it's done.

**Comment by lizzieinvancouver** [comment]
@MoralesCastilla @AileneKane 
I don't think that lines 197-204 work fine exactly, I think they DO delete some treatments but given that 10% budburst is really low, I think it is okay to lose these lines, I added a note to the file. 

Let me and Ailene know when you have finished removing code related target.multiresp=multi_respvar.simple so that Ailene can check the code, then bounce to me to finalize!

**Comment by MoralesCastilla** [comment]
@lizzieinvancouver @AileneKane 
 The code related to target.multiresp=multi_respvar.simple has now been removed. I guess Ailene can now check it and bounce.

**Comment by AileneKane** [comment]
I just finished checking it and it looks good to me! 

The only question I have is that there are many different "phenstages" after this code has run. Is it worth checking if any of them are budburst? I think this has been done already elsewhere, but if it seems worthwhile, I can go back and check them. They are from the following papers: "cannell83"   "gansert02"   "gunderson12" "pagter15"    "pettersen71" "sonsteby13"

**Comment by lizzieinvancouver** [comment]
@AileneKane  

From Cat's clean_phenstage.R file:
cannell83: not a useful daystobudburst conversion
gansert02: we could use budstages 2-3  (rest we cannot use)
# gunderson12: budburst is defined as stage 4 which is plotted in Figure 2 and is already recorded in ospree dataset
# pettersen71: flowers - can't fix
# pagter15: Between budstage 1 and 2 is considered budburst  (rest we cannot use)
# sonsteby13: flowers - can't fix

So, we have done what we can!
